# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder "..", "/home/vagrant/Gnbsim_5G"
  config.vm.box = "ubuntu/bionic64"

  config.vm.define :gnbsim5g, autostart: false do |gnbsim5g|
    gnbsim5g.vm.hostname = "gnbsim5g"
    gnbsim5g.vm.network "private_network", ip: "192.168.60.111", nic_type: "82540EM"
    gnbsim5g.vm.network "private_network", ip: "192.168.129.11", nic_type: "82540EM"

    gnbsim5g.vm.provider "virtualbox" do |vb|
      vb.name = "gnbsim5g"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end
